name: CD Delivery

on:
  workflow_run:
    workflows: ["CI devops 2025"] 
    types:
      - completed

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-24.04
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
  
      - name: Build image and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./simple-api
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-simple-api-backend:latest
          push: ${{ github.ref == 'refs/heads/main' }}
  
      - name: Build and push database image
        uses: docker/build-push-action@v6
        with:
          context: ./database
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-database:latest
          push: ${{ github.ref == 'refs/heads/main' }}
  
      - name: Build and push httpd image
        uses: docker/build-push-action@v6
        with:
          context: ./http-server
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-httpd:latest
          push: ${{ github.ref == 'refs/heads/main' }}
