name: Deploy to Remote Server

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    name: Deploy with Ansible
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i inventories/setup.yml playbook.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        working-directory: ./ansible