name: CD Deploy

on:
  workflow_run:
    workflows: ["CD Delivery"] 
    types:
      - completed

jobs:
  deploy:

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Create SSH key file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i inventories/setup.yml playbook.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        working-directory: ./ansible