name: CI devops 2025

on:
  # To begin, you want to launch this job on push and pull request to main and develop branches
  push:
    branches: 
      - main
      - develop
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: simple-api
    steps:
      # Checkout your GitHub code using actions/checkout@v4
      - uses: actions/checkout@v4

      # Do the same with another action (actions/setup-java@v4) that enables setting up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Finally build your app with the latest command
      - name: Build and test with Maven
        run: mvn clean verify
      
  SonarCloud-Scan:
    needs: test-backend
    if: github.ref == 'refs/heads/main'  # Only on main branch
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: simple-api

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=gabwlg_tp-devops-correction-docker -Dsonar.organization=gabwlg -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }} --file ./pom.xml