name: CI devops 2025

on:
  # To begin, you want to launch this job on push and pull request to main and develop branches
  push:
    branches: 
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test-backend: 
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: simple-api
    steps:
      # Checkout your GitHub code using actions/checkout@v4
      - uses: actions/checkout@v4

      # Do the same with another action (actions/setup-java@v4) that enables setting up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Finally build your app with the latest command
      - name: Build and test with Maven
        run: mvn clean install

build-and-push-docker-image:
  needs: test-backend
  runs-on: ubuntu-24.04

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build image and push backend
      uses: docker/build-push-action@v6
      with:
        context: ./simple-api
        push: false  # Set to true if you want to push to Docker Hub
        tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-simple-api-backend:latest

    - name: Build image and push database
      uses: docker/build-push-action@v6
      with:
        context: ./database
        push: false
        tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-simple-api-database:latest

    - name: Build image and push httpd
      uses: docker/build-push-action@v6
      with:
        context: ./http-server
        push: false
        tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-simple-api-httpd:latest
